### ISSUE TITLE
Single quotes being added twice in insert mode

### ISSUE THREAD

**Issue by fabioxgn** [petdr/vide#2]
When in insert mode, if I type a single quote `'` using a us-international keyboard, the char is added twice.

I noticed that the cause is this code: https://github.com/petdr/vide/blob/master/Source/ViBindings.pas#L455

```Delphi
else if not ((ssCtrl in Shift) or (ssAlt in Shift)) then
    begin
      GetKeyboardState(keyState);
      ToAsciiResult := ToAscii(Key, ScanCode, keystate, @c, 0);
      // XXX do we handle the case of two characters in the buffer?
      if (ToAsciiResult > 0) then
      begin
        if (Key = VK_BACK) then
          SetLength(FInsertText, Length(FInsertText) - 1)
        else
          FInsertText := FInsertText + c;
      end;
```

If I remove this, everything works fine, as this code is only executed in insert mode.

The question is why is this code needed? Can't we just let Delphi handle the insert mode?

**Comment by petdr** [comment]
Just though of another thing, if you're in command mode and you type 'e which is go to position e in the file.  Is that possible with US international keyboard?

**Comment by fabioxgn** [comment]
@petdr in vim it is, it works as expected.

I tested here with your original code, and it doesn't work with an internation keyboard, when I type 'e nothing happens.

I also tested with an ABNT2 keyboard and it works as expected.

I then removed this code and tested on both keyboards, got the same result, works in ABNT2 without this code and doesn't work in US International.

**Comment by fabioxgn** [comment]
@petdr I did some testing yesterday and I think that the best approach to handle this is to handle the `WM_DEADCHAR` windows message, this message is received when I press a dead key like `'`, I did some testing and handling this message works.

**Comment by petdr** [comment]
Excellent find.  Thanks for all your hard work.

**Comment by fabioxgn** [comment]
@petdr thanks, I'll try to fix this behaviour this weekend, I've found some other bugs like the identation on pasting and some other things, as it is very time consuming to send a PR for each of modification separately, I'm implementing everything in my fork: https://github.com/fabioxgn/vide

Then if you'd like to test my changes and maybe incorporate in your repository I can send a PR.

For now, my goal is to make everything that you had implemented work just like vim (some things like pasting, or deleting with `x` are buggy, I'm fixing them) and I'm implementing other motions that I use a lot.

I think that this weekend I'll have a lot of new things working, I also updated the README on my fork with the features that are implemented and others than I plan to implemente, please, take a lot :)

And thanks for you work on this, this was something I've wanted for some time now, but didn't know where to start.

**Comment by petdr** [comment]
I just had a quick look, and looks like you've solved the pasting issue which annoyed me but not enough to fix it, I just got very good at deleting or adding back in whitespace quickly.

Orginally I hacked the cnpack project to add vim bindings, but then keeping it in sync became a pain so finally when we upgraded delphi at work, I finally pulled it all out into it's own project and put it here.

I will just merge all your changes once you're happy that they're working well.

Looking forward to seeing what is implemented.

**Comment by fabioxgn** [comment]
@petdr thanks. Yes, the pasting was messing the identation.

I'll just implement a few more things that a miss, like yanking, and maybe adventure a little trying to implement a visual mode too, then I'll organize everything and send a PR. 

I'll close this issue for now, and will try to fix the mark move which I broke to fix this one.
