### ISSUE TITLE
Characters typed on normal mode being inserted

### ISSUE THREAD

**Issue by afarah1** [petdr/vide#4]
On Delphi 10.1 Berlin (24.0.22858.6822) with the latest version from this repository, insert mode works as expected. On normal mode, when clicking "j" to move the cursor down one line it in fact goes down one line, but also inserts a "j" in the cursor position, the same with other keys ("w" moves a word forward but also inserts a "w", etc), as if it was both on normal and on insert mode.

**Comment by petdr** [comment]
I have Delphi 10.1 (not update 2) and it works for me.  You can setup a debug build and try and work out what is going on.  I could also send you the DLLs that I use and you could try installing those.

As I no longer use Delphi heavily I no longer intend to do any more development on this project.
